site_name: BOBs Repository
theme: readthedocs
plugins:
  - search
docs_dir: docs
nav:
  - Access the Repository: data_access.md
  - Contribute to the Repository: contribute.md
  - Additional Resources: resources.md
      
