site_name: BOBs Repository
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: '🔗' 

extra_javascript:
  - js/extra.js

plugins:
  - search
docs_dir: docs
nav:
  - Overview: index.md
  - View or Download Repository: data_access.md
  - Contribute to the Repository: contribute.md
  - Additional Resources: resources.md
      
